from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy import DateTime, func
from datetime import datetime

class Base(DeclarativeBase):
    pass


""" 
Use SQLAlchemy model for:
column name
column type
not null
default values
primary key

Use Pydantic schema for:
required vs optional
string length
min/max values
pattern/format validation
custom business rules 
"""


class Product(Base):
    """Database table for products."""

    __tablename__ = "products_2"

    id: Mapped[int] = mapped_column(primary_key=True)
    name: Mapped[str] = mapped_column(nullable=False)
    description: Mapped[str | None] = mapped_column(nullable=True)
    price: Mapped[float] = mapped_column(nullable=False)
    stock_quantity: Mapped[int] = mapped_column(nullable=False)
    is_active: Mapped[bool] = mapped_column(default=True, nullable=False)
    created_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), nullable=False)
    updated_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), server_default=func.now(), onupdate=func.now(), nullable=False)


# Primary key and datetime arguments are created by themselves if not specified. 
# The default values are set in the database, so they will be automatically generated when a new record is inserted. The `server_default` argument is used to specify a default value that will be generated by the database server, while the `onupdate` argument is used to specify a value that will be updated automatically whenever the record is updated.